spring:
  application:
    name: eureka-server
  profiles:
    active: peer1

server:
  port: 1001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka
