spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9001
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka,http://localhost:1002/eureka
server:
  port: 2001