# 定义Spring应用名称，它是一个微服务的名称，可以有许多实例
spring:
  application:
    name: eureka-server
  profiles:
    active: peer2
#server:
#  port: 5001
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.100:5001/eureka/,http://192.168.1.100:5002/eureka/
    instance:
      hostname: 192.168.1.100
